// <auto-generated />
namespace DHDCShop.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class decimal_rating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(decimal_rating));
        
        string IMigrationMetadata.Id
        {
            get { return "202212201407338_decimal_rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
