// <auto-generated />
namespace DHDCShop.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatenation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatenation));
        
        string IMigrationMetadata.Id
        {
            get { return "202211241842576_update-nation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
