// <auto-generated />
namespace DHDCShop.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change_name_blog_DatePost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_name_blog_DatePost));
        
        string IMigrationMetadata.Id
        {
            get { return "202211040701094_Change_name_blog_DatePost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
