name: Deploy ASP.NET MVC to Somee

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Hoặc version mà bạn đang dùng

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish solution
        run: dotnet publish -c Release -o publish_output

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ftp://dhdcstore.somee.com  # Thay bằng server FTP của bạn
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: publish_output
          server-dir: / # Thay bằng đường dẫn thư mục trên server của bạn
